import 'fake-indexeddb/auto';
import { AccountRepository } from './account-repository';
import { AccountReads } from './account-reads';
import { ensureProfileTimeZoneAfterBootstrap } from './bootstrap';
import { createWorkoutPage } from '../ui/pages/workout';
import { createUiState } from '../ui/state';
import type { PageContext } from '../ui/context';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { db } from '../db';
import { SyncService } from '../services/sync';
import { StorageService } from './storage';
vi.mock('../auth', () => ({ authorizedApiFetch: vi.fn(), clearAuthState: vi.fn(), getCurrentUser: () => null, hasActiveSession: () => true, hasVerifiedOnlineAccount: () => false, resolveApiUrl: (s: string) => s }));
let service: StorageService;
const stamp = '2026-01-01T21:30:00Z';
beforeEach(async () => {
    service = new StorageService({ enableBroadcast: false });
    await service.activate(`time-${Math.random()}`);
    await db.profile.put({ id: 'me', timeZone: 'Europe/Moscow', isPublic: false, createdAt: stamp, updatedAt: stamp });
    await service.reloadCache();
});
afterEach(() => { service.dispose(); vi.useRealTimers(); vi.restoreAllMocks(); document.body.innerHTML = ''; });
const workout = (id: string, date = stamp, isManual = false) => ({ id, startTime: date, endTime: date, status: 'finished' as const, isManual, pauseIntervals: [], updatedAt: stamp });
const log = (id: string, workoutId: string, date = stamp) => ({ id, workoutId, workoutTypeId: 'time', date, durationSeconds: 30, updatedAt: stamp });
async function seed() {
    await db.workouts.bulkPut([workout('old'), workout('new', '2026-01-02T23:00:00Z'), workout('manual', stamp, true)]);
    await db.logs.bulkPut([log('a', 'old'), log('b', 'old', '2026-01-01T22:30:00Z'), log('c', 'new', '2026-01-02T23:00:00Z'), log('d', 'manual')]);
    await service.reloadCache();
}
describe('transactional training dates and actual form measurement updates', () => {
    it.each([60, 100, 3600])('normalizes %i seconds on form creation and editing before persistence', async seconds => {
        await db.workoutTypes.put({ id: 'time', name: 'Time', category: 'time', updatedAt: stamp });
        await service.reloadCache();
        document.body.innerHTML = `<form><input name="typeId" value="time"><input name="duration_hours" value="1"><input name="duration_minutes" value="2"><input name="duration_seconds" value="${seconds}"></form>`;
        const form = document.querySelector('form')!;
        const state = createUiState();
        const page = createWorkoutPage({ state, dependencies: { storage: service }, actions: { showToast: vi.fn(), render: () => {} } } as unknown as PageContext);
        await page.submitLog(form, new Event('submit', { cancelable: true }));
        const created = (await db.logs.toArray())[0];
        expect(created).toMatchObject({ duration: 62 + Math.floor(seconds / 60) });
        expect(created.durationSeconds).toBe(seconds % 60 || undefined);
        state.editingLogId = created.id;
        (form.elements.namedItem('duration_seconds') as HTMLInputElement).value = String(seconds + 60);
        await page.submitLog(form, new Event('submit', { cancelable: true }));
        const edited = await db.logs.get(created.id);
        expect(edited).toMatchObject({ duration: 63 + Math.floor(seconds / 60) });
        expect(edited?.durationSeconds).toBe(seconds % 60 || undefined);
        expect((await db.dirtyEntities.toArray()).some(x => x.key === `logs:${created.id}`)).toBe(true);
        page.dispose();
    });
    it('persists browser fallback once after bootstrap and preserves a newer explicit choice', async () => {
        await db.profile.update('me', { timeZone: undefined });
        await service.reloadCache();
        const repository = new AccountRepository();
        const reads = new AccountReads(repository, () => {});
        await reads.reload();
        const browserZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
        expect(service.getTimeZone()).toBe(browserZone);
        await ensureProfileTimeZoneAfterBootstrap(repository, reads);
        expect((await db.profile.get('me'))?.timeZone).toBe(browserZone);
        expect((await db.dirtyEntities.toArray()).map(x => x.key)).toEqual(['profile:me']);
        await db.profile.update('me', { timeZone: undefined }); await service.reloadCache();
        await reads.reload();
        await db.profile.update('me', { timeZone: 'Pacific/Auckland' });
        await ensureProfileTimeZoneAfterBootstrap(repository, reads);
        expect((await db.profile.get('me'))?.timeZone).toBe('Pacific/Auckland');
    });

    it('groups new implicit logs by account day even across UTC midnight', async () => {
        vi.useFakeTimers({ toFake: ['Date'] }); vi.setSystemTime(new Date(stamp));
        const first = await service.addLog({ workoutTypeId: 'time', durationSeconds: 30 });
        vi.setSystemTime(new Date('2026-01-02T01:30:00Z'));
        const second = await service.addLog({ workoutTypeId: 'time' });
        expect(second.workoutId).toBe(first.workoutId);
        expect(service.getWorkoutDuration(service.getWorkouts()[0])).toBe(240);
    });
    it('moves implicit bounds and tombstones the last empty source; manual bounds stay unchanged', async () => {
        await seed();
        await service.updateLog({ ...service.getLogs().find(l => l.id === 'a')!, date: '2026-01-02T21:30:00Z' });
        expect((await db.logs.get('a'))?.workoutId).toBe('new');
        expect((await db.workouts.get('old'))?.startTime).toBe('2026-01-01T22:30:00Z');
        expect((await db.workouts.get('new'))?.startTime).toBe('2026-01-02T21:30:00Z');
        await service.updateLog({ ...service.getLogs().find(l => l.id === 'b')!, date: '2026-01-02T22:00:00Z' });
        expect((await db.workouts.get('old'))?.isDeleted).toBe(true);
        const manual = await db.workouts.get('manual');
        await service.updateLog({ ...service.getLogs().find(l => l.id === 'd')!, date: '2026-02-01T12:00:00Z' });
        expect(await db.workouts.get('manual')).toEqual(manual);
        expect((await db.dirtyEntities.toArray()).map(x => x.key).sort()).toEqual(['logs:a', 'logs:b', 'logs:d', 'workouts:new', 'workouts:old']);
    });
    it('rolls back logs and both session bounds when the outbox write fails', async () => {
        await seed();
        const before = { logs: await db.logs.toArray(), workouts: await db.workouts.toArray() };
        vi.spyOn(SyncService.prototype, 'markDirtyMany').mockRejectedValue(new Error('outbox failure'));
        await expect(service.updateLog({ ...service.getLogs()[0], date: '2026-03-01T12:00:00Z' })).rejects.toThrow('outbox failure');
        expect(await db.logs.toArray()).toEqual(before.logs);
        expect(await db.workouts.toArray()).toEqual(before.workouts);
        expect(await db.dirtyEntities.count()).toBe(0);
    });
    it('actual DOM submit clears 30 seconds to zero, clears category fields, and moves dates in fake IndexedDB', async () => {
        await seed();
        await db.workoutTypes.bulkPut([{ id: 'time', name: 'Time', category: 'time', updatedAt: stamp }, { id: 'strength', name: 'Strength', category: 'strength', updatedAt: stamp }]);
        await service.reloadCache();
        document.body.innerHTML = '<form><input name="typeId" value="time"><input name="duration_seconds" value="0"><input name="date" value="2026-01-03T00:30"><input name="weight" value="20"><input name="reps" value="5"></form>';
        const form = document.querySelector('form')!;
        let pending: Promise<void>;
        const state = createUiState();
        state.editingLogId = 'a';
        const page = createWorkoutPage({ state, dependencies: { storage: service }, actions: { showToast: vi.fn(), render: () => {} } } as unknown as PageContext);
        form.addEventListener('submit', e => { pending = page.submitLog(form, e); });
        const submit = async () => { form.dispatchEvent(new Event('submit', { cancelable: true })); await pending; };
        await submit();
        expect(await db.logs.get('a')).toMatchObject({ duration: 0, durationSeconds: undefined, workoutId: 'new', date: '2026-01-02T21:30:00.000Z' });
        (form.elements.namedItem('typeId') as HTMLInputElement).value = 'strength';
        await submit();
        expect(await db.logs.get('a')).toMatchObject({ weight: 20, reps: 5, duration: undefined, durationSeconds: undefined });
        (form.elements.namedItem('typeId') as HTMLInputElement).value = 'time';
        await submit();
        expect(await db.logs.get('a')).toMatchObject({ weight: undefined, reps: undefined, duration: 0 });
        expect((await db.dirtyEntities.toArray()).map(x => x.key).sort()).toEqual(['logs:a', 'workouts:new', 'workouts:old']);
    });
});
